{{- if .Values.ingress.enabled -}}
{{- range .Values.ingress.hosts }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
spec:
  ingressClassName: {{ .className }}
  tls:
  - hosts:
    - {{ .host }}
    secretName: {{ .secretName }}
  rules:
    - host: {{ .host }}
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
            path: {{ .path }}
---
{{- end }}
{{- end -}}