apiVersion: v1
kind: Service
metadata:
  name: {{ include "appdeploy.fullname" . }}
  labels:
    {{- include "appdeploy.labels" . | nindent 4 }}
spec:
  # The type of Service (ClusterIP, NodePort, LoadBalancer, or ExternalName)
  type: {{ .Values.service.type }} 
  ports:
    - port: {{ .Values.service.port }}            # The port the Service exposes (e.g., 80)
      targetPort: http                            # Matches the name 'http' in the Deployment's container ports
      protocol: TCP
      name: http
  selector:
    {{- include "appdeploy.selectorLabels" . | nindent 4 }}